<a href="https://colab.research.google.com/github/NadaMagdy-hub/Olist-E-Commerce-Data-Analysis/blob/main/Products.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re

In [ ]:
Products= pd.read_csv("/content/olist_products_dataset.csv")

In [ ]:
Products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [ ]:
Products.tail()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [ ]:
 Products.columns.tolist()

['product_id',
 'product_category_name',
 'product_name_lenght',
 'product_description_lenght',
 'product_photos_qty',
 'product_weight_g',
 'product_length_cm',
 'product_height_cm',
 'product_width_cm']

In [ ]:
Products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [ ]:
Products.shape

(32951, 9)

In [ ]:
Products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [ ]:
Products.isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [ ]:
Products.duplicated().sum()

np.int64(0)

In [ ]:
Products.product_id.duplicated().sum()

np.int64(0)

-----تنظيف وتوحيد نصوص أسماء التصنيفات------

In [ ]:
Products['product_category_name'] = Products['product_category_name'].astype(str).str.strip().str.lower()

------معالجة القيم المفقودة في اسم التصنيف
بما إن pandas بيحول الـ NaN لـ 'nan' كـ string بعد الـ astype(str)، هنستبدلها بـ 'unknown'-----

In [ ]:
Products['product_category_name'] = Products['product_category_name'].replace('nan', 'unknown')

-----معالجة القيم المفقودة لأعمدة الخصائص الأخرى (الصور والأطوال)-------

In [ ]:
Products['product_name_lenght'] = Products['product_name_lenght'].fillna(0).astype('Int64')
Products['product_description_lenght'] = Products['product_description_lenght'].fillna(0).astype('Int64')
Products['product_photos_qty'] = Products['product_photos_qty'].fillna(0).astype('Int64')

--------معالجة الأوزان والأبعاد المفقودة (بالوسيط Median)-------

In [ ]:
Products['product_weight_g'] = Products['product_weight_g'].fillna(Products['product_weight_g'].median())
Products['product_length_cm'] = Products['product_length_cm'].fillna(Products['product_length_cm'].median())
Products['product_height_cm'] = Products['product_height_cm'].fillna(Products['product_height_cm'].median())
Products['product_width_cm'] = Products['product_width_cm'].fillna(Products['product_width_cm'].median())

In [ ]:
Products.to_csv('cleaned_products.csv', index=False)